### ISSUE TITLE
Extension bootup failed => dependency error(lodash is missing)

### ISSUE THREAD

**Issue by andischerer** [eamodio/vscode-gitlens#7]
Hey there,
many thanks for this awesome plugin. 👍 

Since v0.3.1 im getting a dependency error on vscode startup. Looks like spawn-rx requires lodash as dependency. 

![image](https://cloud.githubusercontent.com/assets/930604/18664161/d16d2f18-7f21-11e6-81e3-7f3457f569bb.png)

Used vscode version:
Version 1.5.2
Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
Date 2016-09-12T13:30:03.456Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by con-ssc** [comment]
Second that
![image](https://cloud.githubusercontent.com/assets/8189808/18664354/8efcdb0a-7f22-11e6-9a3b-ffcd6d2bee05.png)

**Comment by con-ssc** [comment]
Great!

**Comment by con-ssc** [comment]
With that change you are now missing rxjs
[cid:image001.png@01D2135E.B824D1C0]
Von: Eric Amodio [mailto:notifications@github.com]
Gesendet: Dienstag, 20. September 2016 16:21
An: eamodio/vscode-gitlens <vscode-gitlens@noreply.github.com>
Cc: Stefan Schneider <Stefan.Schneider@connectiv.de>; Comment <comment@noreply.github.com>
Betreff: Re: [eamodio/vscode-gitlens] Extension bootup failed => dependency error(lodash is missing) (#7)


Closed #7<https://github.com/eamodio/vscode-gitlens/issues/7> via 20df773<https://github.com/eamodio/vscode-gitlens/commit/20df7732bed4fa50308389ac102c02b71b76f654>.

**Comment by eamodio** [comment]
@con-ssc thanks! that will teach me to not test the built extension :(

**Comment by avih** [comment]
0.3.3 and 0.5.0 don't work on Linux: `mainThreadExtensionService.ts:89Activating extension 'eamodio.gitlens' failed: Cannot find module 'lodash.escapeRegExp'.`

**Comment by eamodio** [comment]
@avih I don't have a way of testing this right now, but I'm pretty sure the issue was the casing on the import. Let me know if v0.5.2 doesn't work

**Comment by avih** [comment]
Confirmed 0.5.2 works on Linux and Windows (0.5.0 worked on Windows but not Linux). Thanks!
